FROM nodered/node-red

RUN npm install \
	node-red-contrib-prometheus-exporter \
	node-red-contrib-google-smarthome \
	node-red-contrib-bigtimer \
  node-red-contrib-google-sheets \
  node-red-contrib-tplink

